version: 2
updates:
  - package-ecosystem: yarn
    directory: "/dapp"
    schedule:
      cron: 0 14 * * *
    range: '>= {major}.{minor}, < {major+1}.0.0'
  - package-ecosystem: yarn
    directory: "/faucet"
    schedule:
      cron: 0 14 * * *
    range: '>= {major}.{minor}, < {major+1}.0.0'
  - package-ecosystem: yarn
    directory: "/subgraph"
    schedule:
      cron: 0 14 * * *
    range: '>= {major}.{minor}, < {major+1}.0.0'