version: 2
updates:
  # Python / Django Backend
  - package-ecosystem: "npm"
    directory: "/dapp-v1"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "npm"
    directory: "/subgraph"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "npm"
    directory: "/contracts"
    schedule:
      interval: "weekly"
      day: "saturday"
