version: 2
updates:
  # Python / Django Backend
  - package-ecosystem: "npm"
    directory: "/dapp-v1"
    schedule:
      interval: "daily"
    labels: []
  - package-ecosystem: "npm"
    directory: "/subgraph"
    schedule:
      interval: "daily"
    labels: []
  - package-ecosystem: "npm"
    directory: "/contracts"
    schedule:
      interval: "daily"
    labels: []
