name: Dapp CI
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install node_modules
      working-directory: ./
      run: yarn dapp install
    - name: Run Biome
      working-directory: ./
      run: yarn dapp format; yarn dapp lint;
    - name: Build checks
      env: # Or as an environment variable
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        VITE_GRAPHQL_ENDPOINT: https://api.thegraph.com/subgraphs/name/crypto-rizzo/nftyfinance-base-sepolia
      working-directory: ./
      run: yarn dapp build;
