name: Scanner App CI
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install node_modules
      working-directory: ./faucet
      run: yarn install
    - name: Run ESlint checks
      working-directory: ./faucet
      run: yarn format:write;
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install node_modules
      working-directory: ./faucet
      run: yarn install
    - name: Run TypeScript type checks
      working-directory: ./faucet
      run: yarn tsc;
