name: Faucet CI
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install node_modules
      working-directory: ./
      run: yarn faucet install
    - name: Run Biome + TSC checks
      working-directory: ./
      run: yarn faucet format; yarn faucet lint; yarn faucet tsc;
